{% set name = "praatio" %}
{% set version = "6.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ed8fdee6121bdae142817879ed9a50cc8334e72c03c110162e21ed8160180d2a

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - typing-extensions
  run:
    - python >={{ python_min }}
    - typing-extensions

test:
  requires:
    - python {{ python_min }}
  imports:
    - praatio
    - praatio.utilities
    - praatio.data_classes

about:
  home: https://github.com/timmahrt/praatIO
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A library for working with praat, time aligned audio transcripts, and audio files that comes with batteries included.
  description: |
    Praat uses a file format called textgrids, which are time aligned speech transcripts. This library isn't just a
    data struct for reading and writing textgrids--many utilities are provided to make it easy to work with with
    transcripts and associated audio files. This library also provides some other tools for use with praat.

    Praat is an open source software program for doing phonetic analysis and annotation of speech. Praat can be
    downloaded here <http://www.fon.hum.uva.nl/praat/>
  doc_url: https://timmahrt.github.io/praatIO/
  dev_url: https://github.com/timmahrt/praatIO

extra:
  recipe-maintainers:
    - timmahrt
    - mmcauliffe
